### ISSUE TITLE
Reboot button doesn't work in AP mode

### ISSUE THREAD

**Issue by rubenfeurer** [rubenfeurer/internetRadio#59]
When AP mode is active, noting happens when pressing the Rotary knob.

**Comment by AmnaNaeem91** [comment]
It is because all the buttons are initiated after Pi is connected to WiFi.
So if you need this functionality before, I will move the Encoder Button
just after the start of software.

This will be done.

**Comment by rubenfeurer** [comment]
> So if you need this functionality before, I will move the Encoder Button
> just after the start of software.

perfect thanks

**Comment by AmnaNaeem91** [comment]
Updated code for this issue has been updated, please adjust those as per
your needs.
