### ISSUE TITLE
Rebooting takes very long

### ISSUE THREAD

**Issue by rubenfeurer** [rubenfeurer/internetRadio#60]
See Video: https://share.icloud.com/photos/002BoNIicuhisyfVmyTusU3Fw

Is there a way to speed up the process? Would it be faster to turn it off and turn it on again?

**Comment by AmnaNaeem91** [comment]
This issue is beyond our software and it has nothing to do with software.
I'm not sure why it is taking this much time to reload.
Please check once you reboot from the terminal it takes the same amount of
time.
Our Software starts action once we are logged into pi.

**Comment by rubenfeurer** [comment]
was able to fix it

**Comment by AmnaNaeem91** [comment]
Hi, how you resolved it and what exactly issue was.
